### ISSUE TITLE
Blank lines make moving cursor in text buggy

### ISSUE THREAD

**Issue by iclems** [firebase/firepad#82] opened 2013-12-02 14:28 UTC
Create two new blank lines
Use "up" arrow to go up...
You go up by two lines! 

If you create many new blank lines, you'll see that you always go up by 2 lines

**Comment by vincentwoo** [comment] 2015-07-23 00:47
Probably fixed back when we did all that work on cursor stuff. Reopen if you still see this!

**Comment by mikagenic** [comment] 2015-11-18 02:09
This is issue is still there. Is there any ideas on how to fix it ?

Another way to reproduce is in https://groups.google.com/forum/#!topic/firepad-io/LqVz3mHTCBY

This is totally confusing to the user who is just scrolling up through a document

**Comment by vincentwoo** [comment] 2015-11-18 03:59
```
(not sure if related to https://github.com/firebase/firepad/issues/209)

To reproduce:

Type:

foo
<blank line>
bar



place the cursor before the 'b' of 'bar'

press up



The cursor will jump to the end of 'foo' instead of to the beginning of the blank line



Any help with this ?
```

I can't reproduce the issue as you describe using the demo pad at https://demo.firepad.io/#say9rRbxEY.

Please try to give more information about codemirror/firepad/browser versions, or link to a codepen/jsfiddle that reliably reproduces the problem.

**Comment by mikagenic** [comment] 2015-11-18 04:08
Ah ! 

You can see this issue on the firepad demo site https://firepad.io
And it is also happening in my implementation.

What would be the difference to yours ?

**Comment by mikagenic** [comment] 2015-11-18 04:14
Oh this is strange it seems to be intermittent, I could see it ok on yours than started again and the bug appeared

I have left the pad you posted with a sample which works now.
If it doesn't work for you can you please start from scratch:
    Ctrl+A
    backspace
    type: foo
    Hit Enter twice
    type: bar
    Hit Enter
    press up a few times

that should do it I think

**Comment by vincentwoo** [comment] 2015-11-18 04:19
Okay, I see the symptom now, reopening.

**Comment by mikagenic** [comment] 2015-11-18 04:27
Could it be connected to the sentinel ? so that in some way CodeMirror thinks the empty line is not a valid place for the cursor and moves it ?

tracing CodeMirror you can see the cursor jumps after removeChildrenAndAdd is working on the cursorsDiv not sure what's going on

(in: codemirror 

function endOperation_W2(op)
   cm.display.input.showSelection(op.preparedSelection);
       showSelection: function(drawn) {
           removeChildrenAndAdd(display.cursorDiv, drawn.cursors);
              function removeChildrenAndAdd(parent, e) {
)

**Comment by mikagenic** [comment] 2015-11-18 05:05
Another strange observation incase it helps,
if you go before the 'a' in 'bar' and press one it will temporarily 'fix' it. You can then go before the 'b' in 'bar' and go up and everything will be fine. Pressing ctrl+End will again break it.

**Comment by mikagenic** [comment] 2015-11-19 01:01
Vincent, I am pretty sure this case is the same as your post in https://github.com/codemirror/CodeMirror/issues/2635

If I understand correctly the sentinel is implemented as a collapsed range and CM behavior in moving across these ranges is buggy.

How can this be solved. I am thinking of 

- as you are knowledgeable about this perhaps you can post again to CM group describing how the issue becomes severe in FirePad and see if a fix can be made ? I hesitate to post myself as I don't fully understand the issue and how the collapsed range is implemented

- another option is perhaps change FP so that blank lines do not have a sentinel ?

any other ideas ?

**Comment by vincentwoo** [comment] 2015-11-19 01:15
Sorry, I've been busy. I'll try to do some digging soon. You seem to be making good progress diagnosing on your own so far, though, so your continued help is appreciated.

**Comment by mikagenic** [comment] 2015-11-19 01:19
Much appreciated Vincent. Pls also see related (I think) https://github.com/firebase/firepad/issues/209

**Comment by vincentwoo** [comment] 2015-11-24 22:48
This is now fixed on master CodeMirror (which should be out as a release soon): https://github.com/codemirror/CodeMirror/commit/0df380b6384f6138764a2f1c78d960edddf6fbce.

The related bug involving the DEL key is not fixed.

**Comment by mikelehen** [comment] 2015-11-25 01:34
Wow.  Thanks for driving that through @vincentwoo!

**Comment by mikagenic** [comment] 2015-11-25 01:42
Ok I tried using the latest patch from CodeMirror without your commit here (that is with var markerOptions = { inclusiveLeft: true, collapsed: true };)

The original problem is solved but there is now a new as bad issue:

If you type:
foo

bar

and you stand on the 'f' of foo and press the down arrow, the cursor moves to the end of 'foo' instead of the beginning of the blank line.

Can you pls check on your side ?
Thanks!

**Comment by vincentwoo** [comment] 2015-11-25 01:51
oh god, yeah, that's just as bad

**Comment by vincentwoo** [comment] 2015-11-25 02:28
Working on it: https://github.com/codemirror/CodeMirror/issues/3658#issuecomment-159468584

**Comment by vincentwoo** [comment] 2015-11-25 23:07
@mikagenic: The lovely marijnh pushed another fix for us, can you try head CodeMirror again? Thanks for being our QA dept.

**Comment by mikagenic** [comment] 2015-11-25 23:31
Testing with the new patch everything looks fine. Thank you for all the efforts in solving this !

Issue https://github.com/firebase/firepad/issues/209 is surprisingly not solved even though it seems very related. I have a simple PR there to work around the issue by forcing the correct cursor position after DEL but maybe you can have a look to see if it is in fact related to this ?

**Comment by vincentwoo** [comment] 2015-11-25 23:59
I don't think we should force special case cursor movement. I'd rather dig in and figure out why delete has this problem. I imagine it's for similar reasons.

**Closed** 2015-11-25 23:59 UTC

**Comment by mikelehen** [comment] 2015-11-26 00:27
I was thinking about DEL a little and it might be kinda' our fault.  I think when you press DEL, we go from:

    (sentinel}(cursor here)
    (sentinel)next line text

to:

    (sentinel)(cursor here)(sentinel)next line text

But then we have code that merges the sentinel characters into a single atomic range (https://github.com/firebase/firepad/blob/master/lib/rich-text-codemirror.js#L833).  So the cursor ends up in the middle of an atomic range.  And CodeMirror is like WTF? and moves it outside the range.

So I think it may be appropriate to go ahead and hack around this in firepad code.

**Comment by vincentwoo** [comment] 2015-11-26 00:33
hoooo boy. i'll try to take a look at options when i have more time but i'm going to treat this as lower priority than the cursor bug

**Comment by mikelehen** [comment] 2015-11-26 00:47
Yeah, sounds good.  Hackiness abounds, unfortunately. :-(  I think merging @mikagenic's fix would be fine, at least for now.

**Comment by mikagenic** [comment] 2015-11-26 03:15
Thx vincent I have verified and the PR https://github.com/mikagenic/firepad/commit/8150a235f04ccf79d48b4c06dbcb09702f4b2ffd

Works as expected with the latest CodeMirror patch
