### ISSUE TITLE
atNewLine bug

### ISSUE THREAD

**Issue by kofifus** [firebase/firepad#215] opened 2015-12-10 06:26 UTC
line 5166 in firepad.js, function firepad.textPiecesToInserts reads:
```
    atNewLine = string[string.length-1] === '\n';
```
This does not check that string is valid and I have seen cases where I get an error in the console at this line because string.length is not defined

What would be the correct fix ? I was thinking of 
```
   atNewLine = !string || (string[string.length-1] === '\n');
```
should that provide correct behavior ?

**Comment by mikelehen** [comment] 2015-12-10 17:23
Hrm.  That code clearly expects string to be defined.  I'd try to figure out why it's not.  Do you have a way to reproduce the error?

**Comment by mikelehen** [comment] 2016-01-04 23:44
Were you able to reproduce this / isolate the issue?  Else, I'll probably close this issue since I'm not sure it's actionable as-is.

**Comment by kofifus** [comment] 2016-01-05 02:23
no I didn't, maybe close it and I'll post again if it pops up

**Closed** 2016-01-05 02:40 UTC
